// <auto-generated />
using System;
using ABCofRealEstate.DataBaseContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ABCofRealEstate.DataBaseContext.Migrations
{
    [DbContext(typeof(RealEstateDataContext))]
    partial class RealEstateDataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ABCofRealEstate.Data.Models.Apartament", b =>
                {
                    b.Property<int>("IdApartament")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdApartament"));

                    b.Property<int?>("ConditionHouse")
                        .HasColumnType("int");

                    b.Property<short>("CountBalcony")
                        .HasColumnType("smallint");

                    b.Property<short>("CountFloorsHouse")
                        .HasColumnType("smallint");

                    b.Property<short>("CountRooms")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("DateTimePublished")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("District")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EmployeeIdEmployee")
                        .HasColumnType("int");

                    b.Property<int?>("IdEmployee")
                        .HasColumnType("int");

                    b.Property<string>("IdsImg")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActual")
                        .HasColumnType("bit");

                    b.Property<bool>("IsCorner")
                        .HasColumnType("bit");

                    b.Property<double>("KitchenArea")
                        .HasColumnType("float");

                    b.Property<double>("LivingSpace")
                        .HasColumnType("float");

                    b.Property<string>("Locality")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<short>("LocatedFloorApartament")
                        .HasColumnType("smallint");

                    b.Property<int?>("MaterialHouse")
                        .HasColumnType("int");

                    b.Property<short>("NumberApartament")
                        .HasColumnType("smallint");

                    b.Property<string>("NumberProperty")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<string>("Street")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("TotalArea")
                        .HasColumnType("float");

                    b.Property<string>("TypeSale")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdApartament");

                    b.HasIndex("EmployeeIdEmployee");

                    b.ToTable("Apartament");
                });

            modelBuilder.Entity("ABCofRealEstate.Data.Models.Area", b =>
                {
                    b.Property<int>("IdArea")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdArea"));

                    b.Property<DateTime>("DateTimePublished")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("District")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EmployeeIdEmployee")
                        .HasColumnType("int");

                    b.Property<int?>("IdEmployee")
                        .HasColumnType("int");

                    b.Property<string>("IdsImg")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActual")
                        .HasColumnType("bit");

                    b.Property<int>("LandArea")
                        .HasColumnType("int");

                    b.Property<string>("Locality")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<string>("Street")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdArea");

                    b.HasIndex("EmployeeIdEmployee");

                    b.ToTable("Area");
                });

            modelBuilder.Entity("ABCofRealEstate.Data.Models.Commertion", b =>
                {
                    b.Property<int>("IdCommertion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCommertion"));

                    b.Property<short>("CountFloorsHouse")
                        .HasColumnType("smallint");

                    b.Property<short>("CountRooms")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("DateTimePublished")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("District")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EmployeeIdEmployee")
                        .HasColumnType("int");

                    b.Property<int?>("IdEmployee")
                        .HasColumnType("int");

                    b.Property<string>("IdsImg")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActual")
                        .HasColumnType("bit");

                    b.Property<bool>("IsCorner")
                        .HasColumnType("bit");

                    b.Property<string>("Locality")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<short>("LocatedFloorApartament")
                        .HasColumnType("smallint");

                    b.Property<int?>("MaterialHouse")
                        .HasColumnType("int");

                    b.Property<string>("NumberProperty")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<double>("RoomArea")
                        .HasColumnType("float");

                    b.Property<string>("Street")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TypeSale")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdCommertion");

                    b.HasIndex("EmployeeIdEmployee");

                    b.ToTable("Commertion");
                });

            modelBuilder.Entity("ABCofRealEstate.Data.Models.Employee", b =>
                {
                    b.Property<int>("IdEmployee")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEmployee"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdImg")
                        .HasColumnType("int");

                    b.Property<int?>("ImageIdImg")
                        .HasColumnType("int");

                    b.Property<int>("JobTitle")
                        .HasColumnType("int");

                    b.Property<string>("NumberPhone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdEmployee");

                    b.HasIndex("ImageIdImg");

                    b.ToTable("Employee");
                });

            modelBuilder.Entity("ABCofRealEstate.Data.Models.Garage", b =>
                {
                    b.Property<int>("IdGarage")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdGarage"));

                    b.Property<DateTime>("DateTimePublished")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("District")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EmployeeIdEmployee")
                        .HasColumnType("int");

                    b.Property<int?>("IdEmployee")
                        .HasColumnType("int");

                    b.Property<string>("IdsImg")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActual")
                        .HasColumnType("bit");

                    b.Property<string>("Locality")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<string>("Street")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdGarage");

                    b.HasIndex("EmployeeIdEmployee");

                    b.ToTable("Garage");
                });

            modelBuilder.Entity("ABCofRealEstate.Data.Models.Hostel", b =>
                {
                    b.Property<int>("IdHostel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdHostel"));

                    b.Property<int?>("ConditionHouse")
                        .HasColumnType("int");

                    b.Property<short>("CountBalcony")
                        .HasColumnType("smallint");

                    b.Property<short>("CountFloorsHouse")
                        .HasColumnType("smallint");

                    b.Property<short>("CountRooms")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("DateTimePublished")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("District")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EmployeeIdEmployee")
                        .HasColumnType("int");

                    b.Property<int?>("IdEmployee")
                        .HasColumnType("int");

                    b.Property<string>("IdsImg")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActual")
                        .HasColumnType("bit");

                    b.Property<bool>("IsCorner")
                        .HasColumnType("bit");

                    b.Property<double>("KitchenArea")
                        .HasColumnType("float");

                    b.Property<double>("LivingSpace")
                        .HasColumnType("float");

                    b.Property<string>("Locality")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<short>("LocatedFloorApartament")
                        .HasColumnType("smallint");

                    b.Property<int?>("MaterialHouse")
                        .HasColumnType("int");

                    b.Property<short>("NumberApartament")
                        .HasColumnType("smallint");

                    b.Property<string>("NumberProperty")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<string>("Street")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("TotalArea")
                        .HasColumnType("float");

                    b.Property<string>("TypeSale")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdHostel");

                    b.HasIndex("EmployeeIdEmployee");

                    b.ToTable("Hostel");
                });

            modelBuilder.Entity("ABCofRealEstate.Data.Models.House", b =>
                {
                    b.Property<int>("IdHouse")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdHouse"));

                    b.Property<double>("Area")
                        .HasColumnType("float");

                    b.Property<int?>("ConditionHouse")
                        .HasColumnType("int");

                    b.Property<short>("CountFloorsHouse")
                        .HasColumnType("smallint");

                    b.Property<short>("CountRooms")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("DateTimePublished")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("District")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EmployeeIdEmployee")
                        .HasColumnType("int");

                    b.Property<double>("GardenSot")
                        .HasColumnType("float");

                    b.Property<int?>("IdEmployee")
                        .HasColumnType("int");

                    b.Property<string>("IdsImg")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActual")
                        .HasColumnType("bit");

                    b.Property<bool>("IsCorner")
                        .HasColumnType("bit");

                    b.Property<double>("KitchenArea")
                        .HasColumnType("float");

                    b.Property<double>("LivingSpace")
                        .HasColumnType("float");

                    b.Property<string>("Locality")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<short>("LocatedFloorApartament")
                        .HasColumnType("smallint");

                    b.Property<int?>("MaterialHouse")
                        .HasColumnType("int");

                    b.Property<string>("NumberProperty")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<string>("Street")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("TotalArea")
                        .HasColumnType("float");

                    b.Property<string>("TypeSale")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdHouse");

                    b.HasIndex("EmployeeIdEmployee");

                    b.ToTable("House");
                });

            modelBuilder.Entity("ABCofRealEstate.Data.Models.Image", b =>
                {
                    b.Property<int>("IdImg")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdImg"));

                    b.Property<byte[]>("DataImg")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("FileName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdImg");

                    b.ToTable("Image");
                });

            modelBuilder.Entity("ABCofRealEstate.Data.Models.Room", b =>
                {
                    b.Property<int>("IdRoom")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRoom"));

                    b.Property<int?>("ConditionHouse")
                        .HasColumnType("int");

                    b.Property<short>("CountBalcony")
                        .HasColumnType("smallint");

                    b.Property<short>("CountFloorsHouse")
                        .HasColumnType("smallint");

                    b.Property<short>("CountRooms")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("DateTimePublished")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("District")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EmployeeIdEmployee")
                        .HasColumnType("int");

                    b.Property<int?>("IdEmployee")
                        .HasColumnType("int");

                    b.Property<string>("IdsImg")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActual")
                        .HasColumnType("bit");

                    b.Property<bool>("IsCorner")
                        .HasColumnType("bit");

                    b.Property<double>("KitchenArea")
                        .HasColumnType("float");

                    b.Property<double>("LivingSpace")
                        .HasColumnType("float");

                    b.Property<string>("Locality")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<short>("LocatedFloorApartament")
                        .HasColumnType("smallint");

                    b.Property<int?>("MaterialHouse")
                        .HasColumnType("int");

                    b.Property<short>("NumberApartament")
                        .HasColumnType("smallint");

                    b.Property<string>("NumberProperty")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<string>("Street")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("TotalArea")
                        .HasColumnType("float");

                    b.Property<string>("TypeSale")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdRoom");

                    b.HasIndex("EmployeeIdEmployee");

                    b.ToTable("Room");
                });

            modelBuilder.Entity("ABCofRealEstate.Data.Models.Apartament", b =>
                {
                    b.HasOne("ABCofRealEstate.Data.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeIdEmployee");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("ABCofRealEstate.Data.Models.Area", b =>
                {
                    b.HasOne("ABCofRealEstate.Data.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeIdEmployee");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("ABCofRealEstate.Data.Models.Commertion", b =>
                {
                    b.HasOne("ABCofRealEstate.Data.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeIdEmployee");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("ABCofRealEstate.Data.Models.Employee", b =>
                {
                    b.HasOne("ABCofRealEstate.Data.Models.Image", "Image")
                        .WithMany()
                        .HasForeignKey("ImageIdImg");

                    b.Navigation("Image");
                });

            modelBuilder.Entity("ABCofRealEstate.Data.Models.Garage", b =>
                {
                    b.HasOne("ABCofRealEstate.Data.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeIdEmployee");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("ABCofRealEstate.Data.Models.Hostel", b =>
                {
                    b.HasOne("ABCofRealEstate.Data.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeIdEmployee");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("ABCofRealEstate.Data.Models.House", b =>
                {
                    b.HasOne("ABCofRealEstate.Data.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeIdEmployee");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("ABCofRealEstate.Data.Models.Room", b =>
                {
                    b.HasOne("ABCofRealEstate.Data.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeIdEmployee");

                    b.Navigation("Employee");
                });
#pragma warning restore 612, 618
        }
    }
}
